# Generated by Django 5.2.6 on 2025-09-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publihsed_date',
            new_name='published_date',
        ),
    ]
